version: '3.4'
services:
  explorer-admin:
    container_name: explorer_admin
    image: "explorer-admin:${TAG:-latest}"
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    environment:
      OPTION: ${OPTION}
      HOST_DIR_PATH: ${HOST_DIR_PATH}
      SSL_ENABLED: ${SSL_ENABLED:-true}
      IS_TESTNET: ${IS_TESTNET:-false}
      BLOCKSCOUT_BACKEND_DOCKER_TAG: ${BLOCKSCOUT_BACKEND_DOCKER_TAG:-2.1.0}
      BLOCKSCOUT_FRONTEND_DOCKER_TAG: ${BLOCKSCOUT_FRONTEND_DOCKER_TAG:-1.0.0}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/skale-explorer/data
    command: "python3 admin/agent.py ${OPTION}"
  nginx:
    image: nginx:1.19.6
    container_name: nginx
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data/nginx/:/etc/nginx/conf.d/:ro
      - ./data/certs:/data/